### PR TITLE
Update to 2.0.1

### LINKED ISSUE #2: Add license file
It is present in the 2.0.1 release

### LINKED ISSUE #3: Remove patch
it will not be needed from 2.0.1 on

### PR DESCRIPTION
**Pull request by bsipocz**
cc @matteobachetti 

close #2 close #3

### CODE REVIEW

**Comment by bsipocz** [comment]
@mwcraig - would it be possible to get travis access to these feedstocks? Currently I can merge (so indeed am a maintainer), but cannot cancel/restart travis jobs).

**Comment by mwcraig** [comment]
@bsipocz -- I can check on that, but in the meantime, there should be a couple more changes...the license file is now in the distribution and the patch can be removed. This would close issues #2 and #3 (which I made mostly to watch them get closed :))

**Comment by mwcraig** [comment]
(if you can fix those things today, great, otherwise I will tomorrow)(I'm planning to write a script to fork/clone/setup remotes for all of these feedstocks).

**Comment by matteobachetti** [comment]
@bsipocz @mwcraig I'm not very familiar with conda-forge. How can I help you guys?

**Comment by mwcraig** [comment]
Typically the only changes that will be needed are those that @bsipocz has done, updating the version number and the checksum. 

Because the original recipe I wrote also had a patch (for the ConfigParser issue) and left out the `license_file` key, there is a little more needed for this one.

But the workflow is typically:

+ Make a new release of your package, upload it to pypi.
+ Open a PR here updating the version number and checksum at the top of the recipe.
+ Wait for the CI services to finish.
+ Merge when the tests have passed.
+ After merging, the packages are automatically built and uploaded to the conda-forge channel on astropy.
+ Once a day a script will run to copy the built packages over to the astropy channel.

Nothing should change for end users...they can still `conda install -c astropy maltpynt` as in the past.

**Comment by mwcraig** [comment]
Incidentally, uploads may be broken on this repository at the moment. There was an issue with the old authorization token for uploads to anaconda.org.

**Comment by mwcraig** [comment]
Disregard the comment about uploads, has been fixed on this repo already.

**Comment by bsipocz** [comment]
@mwcraig - I've already digged up a few scripts to do the updates, but haven't tried them, and probably won't have much time before the coord meeting to play with them. What about a session on it?

There are:
https://github.com/pmlandwehr/tick-my-feedstocks
https://github.com/axiom-data-science/feedstockrot

**Comment by matteobachetti** [comment]
Thanks for the detailed explanation @mwcraig

**Comment by mwcraig** [comment]
@bsipocz -- I meant a script to fork each of the ~40 feedstocks into one's own account on github, clone them to a local directory, and set up the remotes to include origin (your fork) and upstream (the feedstock in the conda-forge org).

I don't want to manually do that much forking 😬

**Comment by mwcraig** [comment]
@matteobachetti -- no problem; I'm going to need to send that out to all the affiliated package authors over the weekend, glad to get feedback on it now!

**Pull request merged**
